---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/kubedata/registry
    server: # your server ip adress
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Ensure no StorageClass is used
