# wordpress-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/kubedata/html
    server: # Your IP 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Ensure no StorageClass is used
